//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA.CheckTrackingPlatform.Common.Resources.Notifications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Bodies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bodies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SA.CheckTrackingPlatform.Common.Resources.Notifications.Bodies", typeof(Bodies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le bordereau de quittances REF #{0} est en cours de traitement comptabilié.
        /// </summary>
        public static string InProgressAccountingDeliverySlip {
            get {
                return ResourceManager.GetString("InProgressAccountingDeliverySlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La quittance REF #{0} est en cours de traitement recouvrement.
        /// </summary>
        public static string InProgressRecoveryQuittance {
            get {
                return ResourceManager.GetString("InProgressRecoveryQuittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le bordereau de quittances REF #{0} est en cours de traitement réassurance.
        /// </summary>
        public static string InProgressReinsuranceDeliverySlip {
            get {
                return ResourceManager.GetString("InProgressReinsuranceDeliverySlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La quittance REF #{0} est en cours de traitement souscription.
        /// </summary>
        public static string InProgressSubscriptionQuittance {
            get {
                return ResourceManager.GetString("InProgressSubscriptionQuittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le bordereau de quittances REF #{0} est passée à la comptabilité pour traitement.
        /// </summary>
        public static string ToDoAccountingDeliverySlip {
            get {
                return ResourceManager.GetString("ToDoAccountingDeliverySlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La quittance REF #{0} est passée à la comptabilité pour traitement.
        /// </summary>
        public static string ToDoAccountingQuittance {
            get {
                return ResourceManager.GetString("ToDoAccountingQuittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La quittance REF #{0} est passée au recouvrement pour traitement.
        /// </summary>
        public static string ToDoRecoveryQuittance {
            get {
                return ResourceManager.GetString("ToDoRecoveryQuittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La quittance REF #{0} est passée à la réassurance pour traitement.
        /// </summary>
        public static string ToDoReinsuranceQuittance {
            get {
                return ResourceManager.GetString("ToDoReinsuranceQuittance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La quittance REF #{0} est passée à la souscription pour traitement.
        /// </summary>
        public static string ToDoSubscriptionQuittance {
            get {
                return ResourceManager.GetString("ToDoSubscriptionQuittance", resourceCulture);
            }
        }
    }
}
