//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA.CheckTrackingPlatform.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DucumentTypeCodeLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DucumentTypeCodeLabels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SA.CheckTrackingPlatform.Common.Resources.DucumentTypeCodeLabels", typeof(DucumentTypeCodeLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note de couverture.
        /// </summary>
        internal static string CoverNote {
            get {
                return ResourceManager.GetString("CoverNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détail du bordereau.
        /// </summary>
        internal static string DeliverySlipDetail {
            get {
                return ResourceManager.GetString("DeliverySlipDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déclaration sur l&apos;honneur.
        /// </summary>
        internal static string HonorDeclaration {
            get {
                return ResourceManager.GetString("HonorDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non défini.
        /// </summary>
        internal static string NotDefined {
            get {
                return ResourceManager.GetString("NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de chèque émis et non reçu par métier.
        /// </summary>
        internal static string NumberOfChecksIssuedButNotAcknowledgedByTheBusinessUnit {
            get {
                return ResourceManager.GetString("NumberOfChecksIssuedButNotAcknowledgedByTheBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de chèques reçu par métier et non envoyés au Burreau d&apos;ordre.
        /// </summary>
        internal static string NumberOfChecksReceivedByBusinessUnitButNotByRegistryOffice {
            get {
                return ResourceManager.GetString("NumberOfChecksReceivedByBusinessUnitButNotByRegistryOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de chèques reçu par Burreau d&apos;ordre et non envoyées aux clients.
        /// </summary>
        internal static string NumberOfChecksReceivedByRegistryOfficeButNotSentToClient {
            get {
                return ResourceManager.GetString("NumberOfChecksReceivedByRegistryOfficeButNotSentToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de chèque reetourné et non envoyées .
        /// </summary>
        internal static string NumberOfReturnedChecksNotYetReceived {
            get {
                return ResourceManager.GetString("NumberOfReturnedChecksNotYetReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autre.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note de règlement.
        /// </summary>
        internal static string SettlementNote {
            get {
                return ResourceManager.GetString("SettlementNote", resourceCulture);
            }
        }
    }
}
