export type ROLE = string;

export enum SCOPE {
  CAN_VIEW_MENU = 'CAN_VIEW_MENU',
};

export const PERMISSIONS: any = {
    // [ROLE.SUBSCRIPTIONS_EXECUTOR]: [SCOPE.CAN_VIEW_MENU],
    // [ROLE.SUBSCRIPTIONS_MANAGER]: [SCOPE.CAN_VIEW_MENU],
    // [ROLE.RECOVERIES_EXECUTOR]: [SCOPE.CAN_VIEW_MENU],
    // [ROLE.RECOVERIES_MANAGER]: [SCOPE.CAN_VIEW_MENU],
    // [ROLE.checkTrackingS_EXECUTOR]: [SCOPE.CAN_VIEW_MENU],
    // [ROLE.checkTrackingS_MANAGER]: [SCOPE.CAN_VIEW_MENU],
    // [ROLE.ACCOUNTING_EXECUTOR]: [SCOPE.CAN_VIEW_MENU],
    // [ROLE.ACCOUNTING_MANAGER]: [SCOPE.CAN_VIEW_MENU],
};

export const MANAGER_ROLES: ROLE[] = [
    // ROLE.SUBSCRIPTIONS_MANAGER,
    // ROLE.RECOVERIES_MANAGER,
    // ROLE.checkTrackingS_MANAGER,
    // ROLE.ACCOUNTING_MANAGER,
];

export const EXECUTOR_ROLES: ROLE[] = [
    // ROLE.SUBSCRIPTIONS_EXECUTOR,
    // ROLE.RECOVERIES_EXECUTOR,
    // ROLE.checkTrackingS_EXECUTOR,
    // ROLE.ACCOUNTING_EXECUTOR,
];
