declare const CIN_REGEX: RegExp;
declare const DEFAULT_REGEX = ".*";
declare const MOBILE_PHONE_REGEX: RegExp;
declare const LANDLINE_PHONE_REGEX: RegExp;
declare const CHECK_ZERO_REGEX_10: RegExp;
declare const CHECK_ZERO_REGEX_15: RegExp;
declare const DIGITS_ONLY_REGEX: RegExp;
declare const DIGITS_THOUSANDS_SEPARATOR: RegExp;
export { CIN_REGEX, DEFAULT_REGEX, MOBILE_PHONE_REGEX, LANDLINE_PHONE_REGEX, CHECK_ZERO_REGEX_10, CHECK_ZERO_REGEX_15, DIGITS_ONLY_REGEX, DIGITS_THOUSANDS_SEPARATOR, };
