// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SA.CheckTrackingPlatform.Contexts.Management.Application;

#nullable disable

namespace SA.CheckTrackingPlatform.Contexts.Management.Application.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Branchs");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Checks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Amount")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("BankId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("BranchId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CheckNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedByFullName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeactivatedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("DeactivatedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeletedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IsDeactivated")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ModifiedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RegisterOrderNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SinisterNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Checks");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("InternalRoles");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByFullName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeactivatedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("DeactivatedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeletedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ElectronicAddress")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsDeactivated")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ModifiedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.HasKey("Id");

                    b.ToTable("InternalUsers");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalUserInternalRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InternalRoleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("InternalUserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("InternalRoleId");

                    b.HasIndex("InternalUserId");

                    b.ToTable("InternalUserInternalRoles");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedByFullName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeactivatedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("DeactivatedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeletedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("InternalRoleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("InternalUserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsDeactivated")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsSeen")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ModifiedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<int?>("NotificationTypeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("InternalRoleId");

                    b.HasIndex("InternalUserId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Timeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CreatedByFullName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeactivatedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("DeactivatedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime?>("DeactivationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeletedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IsDeactivated")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ModifiedByFullName")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)");

                    b.Property<string>("ReasonLabel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("StatusId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CheckId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Timelines");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Checks", b =>
                {
                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Branch");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalUserInternalRole", b =>
                {
                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalRole", "InternalRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("InternalRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalUser", "InternalUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternalRole");

                    b.Navigation("InternalUser");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Notification", b =>
                {
                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalRole", "InternalRole")
                        .WithMany()
                        .HasForeignKey("InternalRoleId");

                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalUser", "InternalUser")
                        .WithMany()
                        .HasForeignKey("InternalUserId");

                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId");

                    b.Navigation("InternalRole");

                    b.Navigation("InternalUser");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Timeline", b =>
                {
                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.Checks", "Check")
                        .WithMany("Timelines")
                        .HasForeignKey("CheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalUser", "User")
                        .WithMany("Timelines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.Checks", b =>
                {
                    b.Navigation("Timelines");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SA.CheckTrackingPlatform.Domains.Management.Entities.InternalUser", b =>
                {
                    b.Navigation("Timelines");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
