//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA.CheckTrackingPlatform.Common.Resources.Canvases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BodyLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BodyLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SA.CheckTrackingPlatform.Common.Resources.Canvases.BodyLabels", typeof(BodyLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessoire.
        /// </summary>
        public static string Accessoire {
            get {
                return ResourceManager.GetString("Accessoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;affaire.
        /// </summary>
        public static string AffaireType {
            get {
                return ResourceManager.GetString("AffaireType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        public static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSURE.
        /// </summary>
        public static string Assure {
            get {
                return ResourceManager.GetString("Assure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date création boredreau .
        /// </summary>
        public static string BordereauCreationDate {
            get {
                return ResourceManager.GetString("BordereauCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N Bordereau .
        /// </summary>
        public static string BordereauRef {
            get {
                return ResourceManager.GetString("BordereauRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branche.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails Cession.
        /// </summary>
        public static string CessionDetails {
            get {
                return ResourceManager.GetString("CessionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAUX CESSION/QP Cie.
        /// </summary>
        public static string CessionRate {
            get {
                return ResourceManager.GetString("CessionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger souscripteur.
        /// </summary>
        public static string ChargerSubscriptor {
            get {
                return ResourceManager.GetString("ChargerSubscriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission .
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMISSION COMPAGNIE.
        /// </summary>
        public static string CommissionCompagnie {
            get {
                return ResourceManager.GetString("CommissionCompagnie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission compagnie en montant (MAD).
        /// </summary>
        public static string CommissionCompagnieMAD {
            get {
                return ResourceManager.GetString("CommissionCompagnieMAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission intermédiaire  ( en % ).
        /// </summary>
        public static string CommissionIntermédiaire {
            get {
                return ResourceManager.GetString("CommissionIntermédiaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission intermédiaire en montant.
        /// </summary>
        public static string CommissionIntermédiaireMAD {
            get {
                return ResourceManager.GetString("CommissionIntermédiaireMAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature devises.
        /// </summary>
        public static string Currrency {
            get {
                return ResourceManager.GetString("Currrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année  ( Année de la date d&apos;émission) .
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Annotation .
        /// </summary>
        public static string DateAnnotation {
            get {
                return ResourceManager.GetString("DateAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date encaissement .
        /// </summary>
        public static string DateEncaissement {
            get {
                return ResourceManager.GetString("DateEncaissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date limite de règlement.
        /// </summary>
        public static string DateLimite {
            get {
                return ResourceManager.GetString("DateLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;émission.
        /// </summary>
        public static string DateMission {
            get {
                return ResourceManager.GetString("DateMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateRV.
        /// </summary>
        public static string DateRV {
            get {
                return ResourceManager.GetString("DateRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise contrevaleur.
        /// </summary>
        public static string DeviseContrevaleur {
            get {
                return ResourceManager.GetString("DeviseContrevaleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFFET.
        /// </summary>
        public static string Effet {
            get {
                return ResourceManager.GetString("Effet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant d&apos;engagement.
        /// </summary>
        public static string EngagementAmount {
            get {
                return ResourceManager.GetString("EngagementAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base d&apos;engagement.
        /// </summary>
        public static string EngagementBase {
            get {
                return ResourceManager.GetString("EngagementBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part filiale.
        /// </summary>
        public static string EngagementBranch {
            get {
                return ResourceManager.GetString("EngagementBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPIR.
        /// </summary>
        public static string Expir {
            get {
                return ResourceManager.GetString("Expir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferme / Tacite.
        /// </summary>
        public static string Ferme {
            get {
                return ResourceManager.GetString("Ferme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE GARANTIE.
        /// </summary>
        public static string GarantyType {
            get {
                return ResourceManager.GetString("GarantyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERMEDIAIRE.
        /// </summary>
        public static string Intermediare {
            get {
                return ResourceManager.GetString("Intermediare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant bordereau.
        /// </summary>
        public static string MontantBordereau {
            get {
                return ResourceManager.GetString("MontantBordereau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant encaissé.
        /// </summary>
        public static string MontantEncaisse {
            get {
                return ResourceManager.GetString("MontantEncaisse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAP Restant.
        /// </summary>
        public static string NAPRestant {
            get {
                return ResourceManager.GetString("NAPRestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net à Payer.
        /// </summary>
        public static string NetPager {
            get {
                return ResourceManager.GetString("NetPager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTENAIRE.
        /// </summary>
        public static string Partenaire {
            get {
                return ResourceManager.GetString("Partenaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code intermédiaire.
        /// </summary>
        public static string PartnerUserCode {
            get {
                return ResourceManager.GetString("PartnerUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date validation virement.
        /// </summary>
        public static string PaymentCreationDate {
            get {
                return ResourceManager.GetString("PaymentCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant à executé.
        /// </summary>
        public static string PaymentExeculte {
            get {
                return ResourceManager.GetString("PaymentExeculte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° virement .
        /// </summary>
        public static string PaymentRef {
            get {
                return ResourceManager.GetString("PaymentRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° POLICE.
        /// </summary>
        public static string PoliceRef {
            get {
                return ResourceManager.GetString("PoliceRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIME  A 100% .
        /// </summary>
        public static string Prime {
            get {
                return ResourceManager.GetString("Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime  A 100 % MAD.
        /// </summary>
        public static string PrimeMAD {
            get {
                return ResourceManager.GetString("PrimeMAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime nette.
        /// </summary>
        public static string PrimeNette {
            get {
                return ResourceManager.GetString("PrimeNette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIME QP SAHAM (MAD).
        /// </summary>
        public static string PrimeSanlamQP {
            get {
                return ResourceManager.GetString("PrimeSanlamQP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime totale.
        /// </summary>
        public static string PrimeTotale {
            get {
                return ResourceManager.GetString("PrimeTotale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Quittance.
        /// </summary>
        public static string QuittanceRef {
            get {
                return ResourceManager.GetString("QuittanceRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REASSUREUR DIRECT.
        /// </summary>
        public static string ReassureurDirect {
            get {
                return ResourceManager.GetString("ReassureurDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.P SANLAM.
        /// </summary>
        public static string SanlamQP {
            get {
                return ResourceManager.GetString("SanlamQP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pourcentage des parts de Sanlam.
        /// </summary>
        public static string SanlamSharePercentage {
            get {
                return ResourceManager.GetString("SanlamSharePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape workflow réas.
        /// </summary>
        public static string WorkFlowStep {
            get {
                return ResourceManager.GetString("WorkFlowStep", resourceCulture);
            }
        }
    }
}
