//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA.CheckTrackingPlatform.Common.Resources.Canvases {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BodyLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BodyLabels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SA.CheckTrackingPlatform.Common.Resources.Canvases.BodyLabels", typeof(BodyLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accessoire.
        /// </summary>
        public static string Accessoire {
            get {
                return ResourceManager.GetString("Accessoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount Ref.
        /// </summary>
        public static string AmountRef {
            get {
                return ResourceManager.GetString("AmountRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annotations.
        /// </summary>
        public static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ASSURE.
        /// </summary>
        public static string Assure {
            get {
                return ResourceManager.GetString("Assure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom Béneficiaire.
        /// </summary>
        public static string BeneficiaryNameRef {
            get {
                return ResourceManager.GetString("BeneficiaryNameRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date création boredreau .
        /// </summary>
        public static string BordereauCreationDate {
            get {
                return ResourceManager.GetString("BordereauCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N Bordereau .
        /// </summary>
        public static string BordereauRef {
            get {
                return ResourceManager.GetString("BordereauRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Branche.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails Cession.
        /// </summary>
        public static string CessionDetails {
            get {
                return ResourceManager.GetString("CessionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TAUX CESSION/QP Cie.
        /// </summary>
        public static string CessionRate {
            get {
                return ResourceManager.GetString("CessionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charger souscripteur.
        /// </summary>
        public static string ChargerSubscriptor {
            get {
                return ResourceManager.GetString("ChargerSubscriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° de chèque.
        /// </summary>
        public static string CheckNumberRef {
            get {
                return ResourceManager.GetString("CheckNumberRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commission .
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à COMMISSION COMPAGNIE.
        /// </summary>
        public static string CommissionCompagnie {
            get {
                return ResourceManager.GetString("CommissionCompagnie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commission compagnie en montant (MAD).
        /// </summary>
        public static string CommissionCompagnieMAD {
            get {
                return ResourceManager.GetString("CommissionCompagnieMAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commission intermédiaire  ( en % ).
        /// </summary>
        public static string CommissionIntermédiaire {
            get {
                return ResourceManager.GetString("CommissionIntermédiaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commission intermédiaire en montant.
        /// </summary>
        public static string CommissionIntermédiaireMAD {
            get {
                return ResourceManager.GetString("CommissionIntermédiaireMAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date De Création.
        /// </summary>
        public static string CreationDateRef {
            get {
                return ResourceManager.GetString("CreationDateRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nature devises.
        /// </summary>
        public static string Currrency {
            get {
                return ResourceManager.GetString("Currrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Année  ( Année de la date d&apos;émission) .
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Annotation .
        /// </summary>
        public static string DateAnnotation {
            get {
                return ResourceManager.GetString("DateAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date encaissement .
        /// </summary>
        public static string DateEncaissement {
            get {
                return ResourceManager.GetString("DateEncaissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date limite de règlement.
        /// </summary>
        public static string DateLimite {
            get {
                return ResourceManager.GetString("DateLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date d&apos;émission.
        /// </summary>
        public static string DateMission {
            get {
                return ResourceManager.GetString("DateMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DateRV.
        /// </summary>
        public static string DateRV {
            get {
                return ResourceManager.GetString("DateRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Devise contrevaleur.
        /// </summary>
        public static string DeviseContrevaleur {
            get {
                return ResourceManager.GetString("DeviseContrevaleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EFFET.
        /// </summary>
        public static string Effet {
            get {
                return ResourceManager.GetString("Effet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant d&apos;engagement.
        /// </summary>
        public static string EngagementAmount {
            get {
                return ResourceManager.GetString("EngagementAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base d&apos;engagement.
        /// </summary>
        public static string EngagementBase {
            get {
                return ResourceManager.GetString("EngagementBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part filiale.
        /// </summary>
        public static string EngagementBranch {
            get {
                return ResourceManager.GetString("EngagementBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EXPIR.
        /// </summary>
        public static string Expir {
            get {
                return ResourceManager.GetString("Expir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ferme / Tacite.
        /// </summary>
        public static string Ferme {
            get {
                return ResourceManager.GetString("Ferme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TYPE GARANTIE.
        /// </summary>
        public static string GarantyType {
            get {
                return ResourceManager.GetString("GarantyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INTERMEDIAIRE.
        /// </summary>
        public static string Intermediare {
            get {
                return ResourceManager.GetString("Intermediare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° de Lot.
        /// </summary>
        public static string LotNumberRef {
            get {
                return ResourceManager.GetString("LotNumberRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant bordereau.
        /// </summary>
        public static string MontantBordereau {
            get {
                return ResourceManager.GetString("MontantBordereau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant encaissé.
        /// </summary>
        public static string MontantEncaisse {
            get {
                return ResourceManager.GetString("MontantEncaisse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NAP Restant.
        /// </summary>
        public static string NAPRestant {
            get {
                return ResourceManager.GetString("NAPRestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Net à Payer.
        /// </summary>
        public static string NetPager {
            get {
                return ResourceManager.GetString("NetPager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PARTENAIRE.
        /// </summary>
        public static string Partenaire {
            get {
                return ResourceManager.GetString("Partenaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code intermédiaire.
        /// </summary>
        public static string PartnerUserCode {
            get {
                return ResourceManager.GetString("PartnerUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date validation virement.
        /// </summary>
        public static string PaymentCreationDate {
            get {
                return ResourceManager.GetString("PaymentCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant à executé.
        /// </summary>
        public static string PaymentExeculte {
            get {
                return ResourceManager.GetString("PaymentExeculte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° virement .
        /// </summary>
        public static string PaymentRef {
            get {
                return ResourceManager.GetString("PaymentRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° POLICE.
        /// </summary>
        public static string PoliceRef {
            get {
                return ResourceManager.GetString("PoliceRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PRIME  A 100% .
        /// </summary>
        public static string Prime {
            get {
                return ResourceManager.GetString("Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prime  A 100 % MAD.
        /// </summary>
        public static string PrimeMAD {
            get {
                return ResourceManager.GetString("PrimeMAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prime nette.
        /// </summary>
        public static string PrimeNette {
            get {
                return ResourceManager.GetString("PrimeNette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PRIME QP SAHAM (MAD).
        /// </summary>
        public static string PrimeSanlamQP {
            get {
                return ResourceManager.GetString("PrimeSanlamQP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prime totale.
        /// </summary>
        public static string PrimeTotale {
            get {
                return ResourceManager.GetString("PrimeTotale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N° Quittance.
        /// </summary>
        public static string QuittanceRef {
            get {
                return ResourceManager.GetString("QuittanceRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à REASSUREUR DIRECT.
        /// </summary>
        public static string ReassureurDirect {
            get {
                return ResourceManager.GetString("ReassureurDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom Destinataire.
        /// </summary>
        public static string RecipientNameRef {
            get {
                return ResourceManager.GetString("RecipientNameRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Q.P SANLAM.
        /// </summary>
        public static string SanlamQP {
            get {
                return ResourceManager.GetString("SanlamQP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pourcentage des parts de Sanlam.
        /// </summary>
        public static string SanlamSharePercentage {
            get {
                return ResourceManager.GetString("SanlamSharePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etape workflow réas.
        /// </summary>
        public static string WorkFlowStep {
            get {
                return ResourceManager.GetString("WorkFlowStep", resourceCulture);
            }
        }
    }
}
