export enum ROLE {
    SUBSCRIPTIONS_EXECUTOR = 'SubscriptionsExecutor',
    SUBSCRIPTIONS_MANAGER = 'SubscriptionsManager',
    RECOVERIES_EXECUTOR = 'RecoveriesExecutor',
    RECOVERIES_MANAGER = 'RecoveriesManager',
    REINSURANCES_EXECUTOR = 'ReinsurancesExecutor',
    REINSURANCES_MANAGER = 'ReinsurancesManager',
    ACCOUNTING_EXECUTOR = 'AccountingExecutor',
    ACCOUNTING_MANAGER = 'AccountingManager',
};

export enum SCOPE {
  CAN_VIEW_MENU = 'CAN_VIEW_MENU',
};

export const PERMISSIONS: any = {
    [ROLE.SUBSCRIPTIONS_EXECUTOR]: [SCOPE.CAN_VIEW_MENU],
    [ROLE.SUBSCRIPTIONS_MANAGER]: [SCOPE.CAN_VIEW_MENU],
    [ROLE.RECOVERIES_EXECUTOR]: [SCOPE.CAN_VIEW_MENU],
    [ROLE.RECOVERIES_MANAGER]: [SCOPE.CAN_VIEW_MENU],
    [ROLE.REINSURANCES_EXECUTOR]: [SCOPE.CAN_VIEW_MENU],
    [ROLE.REINSURANCES_MANAGER]: [SCOPE.CAN_VIEW_MENU],
    [ROLE.ACCOUNTING_EXECUTOR]: [SCOPE.CAN_VIEW_MENU],
    [ROLE.ACCOUNTING_MANAGER]: [SCOPE.CAN_VIEW_MENU],
};

export const MANAGER_ROLES = [
    ROLE.SUBSCRIPTIONS_MANAGER,
    ROLE.RECOVERIES_MANAGER,
    ROLE.REINSURANCES_MANAGER,
    ROLE.ACCOUNTING_MANAGER,
];

export const EXECUTOR_ROLES = [
    ROLE.SUBSCRIPTIONS_EXECUTOR,
    ROLE.RECOVERIES_EXECUTOR,
    ROLE.REINSURANCES_EXECUTOR,
    ROLE.ACCOUNTING_EXECUTOR,
];
